### ISSUE TITLE
Clean up participant list in the evaluation overview

### ISSUE THREAD

**Issue by Jonas960** [thm-mni-ii/feedbacksystem#606] opened 2021-12-10 09:06 UTC
In the course participant list in the course results, the responsive display of the names should be adjusted that they are clearly readable.

**Comment by Jonas960** [comment] 2022-04-27 12:09
is covered by #605

**Comment by mxsph** [comment] 2022-08-01 08:33
Duplicate of #605

**Closed by mxsph** 2022-08-01 08:33 UTC
Labels: duplicate, usability, UI/UX, web-gui
