### ISSUE TITLE
Completely renew API Test, because dev is no gone

### ISSUE THREAD

**Issue by bees4ever** [thm-mni-ii/feedbacksystem#225] opened 2019-03-07 11:53 UTC
- rewrite python script which performs unit tests. We can not use old routes which are gone now (insecure).
- Moreover I though to do some scenarios where one user grants another etc.

**Comment by andrej-sajenko** [comment] 2020-06-23 12:33
possible duplicate of #278

**Closed by andrej-sajenko** 2020-06-23 12:33 UTC
